### PR TITLE
Wip msvc compile

### PR DESCRIPTION
**Pull request by adrido**
Some other fixes for gen-build-config.bat

### CODE REVIEW

**Comment by Rogier-5** [comment]
Thanks **very** much for all the testing / debugging.

I did some reordering and splitting/squashing of commits, to eliminate the unnecessary noise, and so that the  changes will be easier for other people to make sense of. I also made a few documentation changes, and I removed a few redundant lines in one of the MSVC project files.

I think it would be useful to include some information (e.g. a link) in the documentation where somebody interested in compiling on windows might be able to download a suitable version of libdg. Could you give me  link, so that I can include it in the docs; or could you include one yourself ?

If you're fine with the current state of the PR (including my rearrangements and squashes), and with the libdg download info included, then as far as I'm concerned, the PR will ready for merging.

**Comment by adrido** [comment]
> Thanks *very* much for all the testing / debugging.
>
No problem. :-)
>
> I did some reordering and splitting/squashing of commits, to eliminate
> the unnecessary noise, and so that the changes will be easier for
> other people to make sense of. I also made a few documentation
> changes, and I removed a few redundant lines in one of the MSVC
> project files.
>
Its Ok. If the project file is still working I think its ok.
>
> I think it would be useful to include some information (e.g. a link)
> in the documentation where somebody interested in compiling on windows
> might be able to download a suitable version of libdg. Could you give
> me link, so that I can include it in the docs; or could you include
> one yourself ?
>
I can send you a zip file with the libgd.lib/.dll that is build with the
same version of zlib as found in the nuget repo.
>
> If you're fine with the current state of the PR (including my
> rearrangements and squashes), and with the libdg download info
> included, then as far as I'm concerned, the PR will ready for merging.
>
Ill check it again and give my OK in ~2-3 hours

**Comment by Rogier-5** [comment]
> > I think it would be useful to include some information (e.g. a
> > link) in the documentation where somebody interested in compiling
> > on windows might be able to download a suitable version of libdg.
> > Could you give me link, so that I can include it in the docs; or
> > could you include one yourself ?
> 
> I can send you a zip file with the libgd.lib/.dll that is build with
> the same version of zlib as found in the nuget repo.

It's not primarily for my convenience as I can't compile on Windows anyway, 
but for other people who are reading the documentation and wish to 
compile using MSVC. They'll appreciate having a location to go to, instead 
of going through the hassle of searching the internet themselves.

I understood that you obtained the version of libgd somewhere from the 
internet ? Or did you compile it yourself ?

**Comment by adrido** [comment]
I had to compile it by myself, because it must use the same version of zlib as used by minetestmapper. 
But it was easy, because [they](https://github.com/libgd/libgd) provide a working cmakeList.txt.
Also there are no "official" builds for windows.

**Comment by adrido** [comment]
Here are 2 packages of libgd.
Both build on 25.05.2016 with Visual Studio 2015 (vc_140) They contain all files of gd required to build minetestmapper with Visual Studio. Tested with VS 2015. Version is 2.2.1 (even if package-name tells something different :laughing: ) Source code can be found [here](https://github.com/libgd/libgd/releases/tag/gd-2.2.1).
[libgd-2.1.0-win32.zip](https://github.com/Rogier-5/minetest-mapper-cpp/files/281930/libgd-2.1.0-win32.zip)
[libgd-2.1.0-win64.zip](https://github.com/Rogier-5/minetest-mapper-cpp/files/281931/libgd-2.1.0-win64.zip)

@Rogier-5 I think its ready now. except you may have to note something about x64 build:
x64 build might fail due [a bug of snappy](https://bitbucket.org/robertvazan/snappy-visual-cpp/issues/1/snappycc-will-not-compile-on-windows-x64) (required for leveldb). Solution: open `packages\Snappy.1.1.1.7\lib\native\src\snappy.cc` and change line 955 from `#ifndef WIN32` to `#ifndef _WIN32`

**Comment by Rogier-5** [comment]
> Here are 2 packages of libgd.
> Both build on 25.05.2016 with Visual Studio 2015 (vc_140) They
> contain all files of gd required to build minetestmapper with
> Visual Studio. Tested with VS 2015. Version is 2.2.1 (even if
> package-name tells something different :laughing: ) Source code can
> be found
> [here](https://github.com/libgd/libgd/releases/tag/gd-2.2.1).
> [libgd-2.1.0-win32.zip](https://github.com/Rogier-5/minetest-mapper
> -cpp/files/281930/libgd-2.1.0-win32.zip)
> [libgd-2.1.0-win64.zip](https://github.com/Rogier-5/minetest-mapper
> -cpp/files/281931/libgd-2.1.0-win64.zip)

Thanks. I'll make them available for download, for people who want to avoid 
recompiling gd.

> @Rogier-5 I think its ready now. except you may have to note
> something about x64 build: x64 build might fail due [a bug of
> snappy](https://bitbucket.org/robertvazan/snappy-visual-cpp/issues/
> 1/snappycc-will-not-compile-on-windows-x64) (required for leveldb).
> Solution: open `packages\Snappy.1.1.1.7\lib\native\src\snappy.cc`
> and change line 955 from `#ifndef WIN32` to `#ifndef _WIN32`

I'll add it to the manual.

**Pull request closed without merging**
